import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
// POD design system — tokens (CSS variables) + compiled Tailwind utilities.
// Order matters: theme.css first (declares --color-* etc.), then styles.css
// (utility classes that consume those vars).
import "@tally-ui/tokens/theme.css";
import "@tally-ui/ui/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Inter matches POD docs font — POD components rendered in centernode inherit this.
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // Initial `dark` class activates @tally-ui/tokens dark-mode variables
      // across every POD primitive rendered inside centernode. The
      // bootstrap script below reads `centernode-theme` from localStorage
      // and removes the class if user previously toggled to light — runs
      // before React mounts so there's no flash-of-wrong-theme.
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} h-full antialiased dark`}
      suppressHydrationWarning
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function(){
                try{
                  var stored=localStorage.getItem('centernode-theme');
                  if(stored==='light'){document.documentElement.classList.remove('dark');}
                }catch(e){}
              })();
            `,
          }}
        />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
