#!/usr/bin/env node
/**
 * canvas sync — single source of truth for adding components to POD.
 *
 * What it does:
 *   1. Scans `packages/ui/src/<dir>/` for component directories
 *      (must contain index.ts AND canvas.ts to be picked up).
 *   2. Re-generates `packages/ui/src/canvas.ts` (the aggregator).
 *   3. Re-generates `packages/ui/tsup.config.ts` entry list.
 *   4. Re-generates `packages/ui/package.json` `exports` section
 *      (preserves manual fields, only rewrites subpath exports).
 *   5. Re-generates `centernode/src/utils/tallyUiRuntime.js`
 *      imports + POD_COMPONENTS map.
 *
 * Workflow for adding a new component (e.g. Switch):
 *   - Create packages/ui/src/switch/switch.tsx (the component)
 *   - Create packages/ui/src/switch/index.ts  (export { Switch })
 *   - Create packages/ui/src/switch/canvas.ts (canvas metadata)
 *   - Run: node scripts/canvas/sync.mjs
 *   - Done. tsup config, package.json exports, canvas manifest,
 *     centernode runtime — all auto-updated.
 *
 * Idempotent: running it twice with no changes produces no diff.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '../..');
const UI_SRC = path.join(ROOT, 'packages/ui/src');
const UI_PKG = path.join(ROOT, 'packages/ui');
const CENTERNODE_RUNTIME = path.join(ROOT, 'centernode/src/utils/tallyUiRuntime.js');

const SKIP_DIRS = new Set(['lib']);
const SKIP_PREFIX = '_';

// ── Helpers ────────────────────────────────────────────────────────────────
function kebabToCamel(s) {
  return s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}
function kebabToPascal(s) {
  const camel = kebabToCamel(s);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}
function readJSON(p) {
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}
function writeJSON(p, obj) {
  fs.writeFileSync(p, JSON.stringify(obj, null, 2) + '\n');
}

// ── 1. Discover components ─────────────────────────────────────────────────
function discoverComponents() {
  const dirs = fs.readdirSync(UI_SRC, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .filter((name) => !SKIP_DIRS.has(name) && !name.startsWith(SKIP_PREFIX))
    .sort();

  const components = [];
  for (const dir of dirs) {
    const indexFile = path.join(UI_SRC, dir, 'index.ts');
    const canvasFile = path.join(UI_SRC, dir, 'canvas.ts');
    if (!fs.existsSync(indexFile)) continue;
    // Parse canvas.ts for extraScope + name override (cheap regex; canvas.ts is hand-edited TS).
    // The `name:` field is the actual React export — preferred over kebabToPascal(dir)
    // when dir is plural but export is singular (badges→Badge, tabs→Tab).
    let extraScope = [];
    let nameOverride = null;
    if (fs.existsSync(canvasFile)) {
      const src = fs.readFileSync(canvasFile, 'utf8');
      const m = src.match(/extraScope:\s*\[([^\]]+)\]/);
      if (m) {
        extraScope = m[1]
          .split(',')
          .map((s) => s.trim().replace(/^['"]|['"]$/g, ''))
          .filter(Boolean);
      }
      const nameMatch = src.match(/\bname:\s*['"]([A-Z][A-Za-z0-9]*)['"]/);
      if (nameMatch) nameOverride = nameMatch[1];
    }
    components.push({
      dir,                                  // e.g. "text-input"
      varName: `${kebabToCamel(dir)}Canvas`, // e.g. "textInputCanvas"
      componentName: nameOverride ?? kebabToPascal(dir), // e.g. "TextInput", or "Badge" from canvas.ts
      hasCanvasMeta: fs.existsSync(canvasFile),
      extraScope,                           // e.g. ['DropdownMenu', 'DropdownItem']
    });
  }
  return components;
}

// ── 2. Generate src/canvas.ts ──────────────────────────────────────────────
function writeCanvasAggregator(components) {
  const withMeta = components.filter((c) => c.hasCanvasMeta);
  let out = `/* AUTO-GENERATED by scripts/canvas/sync.mjs — DO NOT EDIT.
 * Re-run \`node scripts/canvas/sync.mjs\` after adding/removing component dirs.
 */
import type { CanvasManifest } from './canvas-types.js';
`;
  for (const c of withMeta) {
    out += `import { ${c.varName} } from './${c.dir}/canvas.js';\n`;
  }
  out += `\nexport * from './canvas-types.js';\n`;
  out += `\nexport const canvasManifest: CanvasManifest = {\n`;
  out += `  version: '1',\n`;
  out += `  components: [\n`;
  for (const c of withMeta) {
    out += `    ${c.varName},\n`;
  }
  out += `  ],\n`;
  out += `};\n`;
  fs.writeFileSync(path.join(UI_SRC, 'canvas.ts'), out);
}

// ── 3. Generate tsup.config.ts entries ─────────────────────────────────────
function writeTsupConfig(components) {
  const file = path.join(UI_PKG, 'tsup.config.ts');
  let content = fs.readFileSync(file, 'utf8');

  let entries = `  entry: {\n    index: 'src/index.ts',\n`;
  for (const c of components) {
    entries += `    '${c.dir}': 'src/${c.dir}/index.ts',\n`;
  }
  entries += `    canvas: 'src/canvas.ts',\n  },`;

  content = content.replace(/  entry:\s*\{[\s\S]*?\},/, entries);
  fs.writeFileSync(file, content);
}

// ── 4. Generate package.json exports ───────────────────────────────────────
function writePackageJsonExports(components) {
  const file = path.join(UI_PKG, 'package.json');
  const pkg = readJSON(file);
  const exports = {
    '.': {
      types: './dist/index.d.ts',
      import: './dist/index.mjs',
      require: './dist/index.js',
    },
  };
  for (const c of components) {
    exports[`./${c.dir}`] = {
      types: `./dist/${c.dir}.d.ts`,
      import: `./dist/${c.dir}.mjs`,
      require: `./dist/${c.dir}.js`,
    };
  }
  exports['./canvas'] = {
    types: './dist/canvas.d.ts',
    import: './dist/canvas.mjs',
    require: './dist/canvas.js',
  };
  exports['./styles.css'] = './dist/styles.css';
  pkg.exports = exports;
  writeJSON(file, pkg);
}

// ── 5. Generate centernode tallyUiRuntime.js (POD_COMPONENTS map) ──────────────
function writeCenternodeRuntime(components) {
  if (!fs.existsSync(CENTERNODE_RUNTIME)) return; // optional — only if centernode present

  const withMeta = components.filter((c) => c.hasCanvasMeta);

  let head = `/**
 * POD design system integration for the playground runtime.
 * Components below are AUTO-INJECTED by scripts/canvas/sync.mjs.
 * Any component with a packages/ui/src/<dir>/canvas.ts file shows up here.
 *
 * Manually-maintained: transformIfJSX (sucrase config) and exports below.
 */
`;

  let imports = '';
  for (const c of withMeta) {
    const named = [c.componentName, ...c.extraScope].join(', ');
    imports += `import { ${named} } from "@tally-ui/ui/${c.dir}";\n`;
  }
  imports += `import { canvasManifest } from "@tally-ui/ui/canvas";\n`;
  imports += `import { transform } from "sucrase";\n\n`;

  // POD_COMPONENTS includes primary + all extraScope sub-primitives so composite
  // snippets (function components) can reference DropdownMenu, DropdownItem, etc.
  const allNames = withMeta.flatMap((c) => [c.componentName, ...c.extraScope]);
  const componentEntries = allNames.map((n) => `  ${n}`).join(',\n');
  const podComponentsBlock = `export const POD_COMPONENTS = {\n${componentEntries}\n};\nexport { canvasManifest };\n\n`;

  const tail = `// JSX heuristics — match a tag opener like \`<Button\` or \`<div className\`.
// Cheap pre-filter so we skip sucrase entirely for plain h() code.
const JSX_HINT = /<[A-Z][\\w.]*[\\s/>]|<[a-z][\\w-]*(?:\\s+[\\w-]+\\s*=)/;

export function transformIfJSX(code) {
  if (!JSX_HINT.test(code)) return code;
  try {
    const out = transform(code, {
      transforms: ["jsx", "typescript", "imports"],
      jsxRuntime: "classic",
      jsxPragma: "h",
      jsxFragmentPragma: "Fragment",
      production: true,
    });
    return out.code
      .replace(/^\\s*(?:var|const|let)\\s+\\w+\\s*=\\s*require\\(['"][^'"]+['"]\\);?\\s*$/gm, "")
      .replace(/^\\s*Object\\.defineProperty\\(exports.*$/gm, "")
      .replace(/^\\s*exports\\.\\w+\\s*=.*$/gm, "")
      .replace(/^\\s*"use strict";\\s*$/gm, "");
  } catch (err) {
    throw new Error(\`JSX transform failed: \${err.message}\`);
  }
}

// Names + values for \`new Function(...)\` factory. Order MUST match between
// \`paramNames\` and \`paramValues\` when invoking.
export const POD_SCOPE_NAMES = Object.keys(POD_COMPONENTS);
export const POD_SCOPE_VALUES = Object.values(POD_COMPONENTS);
`;

  fs.writeFileSync(CENTERNODE_RUNTIME, head + imports + podComponentsBlock + tail);
}

// ── Run ────────────────────────────────────────────────────────────────────
function main() {
  const components = discoverComponents();
  console.log(`[canvas-sync] discovered ${components.length} components: ${components.map((c) => c.componentName).join(', ')}`);
  const withMeta = components.filter((c) => c.hasCanvasMeta);
  if (withMeta.length < components.length) {
    const missing = components.filter((c) => !c.hasCanvasMeta).map((c) => c.dir);
    console.log(`[canvas-sync] note: ${missing.join(', ')} missing canvas.ts (they'll still ship to npm but won't show in canvas tools)`);
  }

  writeCanvasAggregator(components);
  console.log('[canvas-sync] wrote packages/ui/src/canvas.ts');

  writeTsupConfig(components);
  console.log('[canvas-sync] wrote packages/ui/tsup.config.ts');

  writePackageJsonExports(components);
  console.log('[canvas-sync] wrote packages/ui/package.json exports');

  writeCenternodeRuntime(components);
  if (fs.existsSync(CENTERNODE_RUNTIME)) {
    console.log('[canvas-sync] wrote centernode/src/utils/tallyUiRuntime.js');
  }

  console.log('[canvas-sync] ✓ done');
}

main();
